<?php

use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_event_subscriber(). Hook to add event subscirber.
 */
function practice_caching_event_subscriber() {
  return [\Drupal\practice_caching\EventSubscriber\CacheControlSubscriber::class];
}

function practice_caching_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $bundle = $entity->bundle();
  //dump($bundle);
  if ($bundle == 'content') {
    $build['#cache']['max-age'] = 0;
    \Drupal::service('page_cache_kill_switch')->trigger();
  }
}
